---
- name: Install prerequisites
  include_tasks: prerequisites.yml

- name: Create user and group
  include_tasks: user.yml

- name: Mount NAS media share
  include_role:
    name: nfs_mount
  vars:
    nfs_mount_lxc_host: alps
    nfs_mount_lxc_shifted_id_report: "{{ sonarr_uid }}"
    nfs_mounts:
      - src: pm-nas-01.home.hooper.co.uk:/mnt/Media
        path: /mnt/Media

- name: Download and extract Sonarr
  include_tasks: download.yml

- name: Install Sonarr
  include_tasks: install.yml

- name: Configure and start Sonarr service
  include_tasks: service.yml

- name: Setup reverse proxy
  include_role:
    name: caddy
  vars:
    caddy_url: lxc-sonarr-01.home.hooper.co.uk
    caddy_ports:
      - port: 8989
