---
- name: Assert nfs_mounts is set
  assert:
    that:
      - nfs_mounts | length > 0
    fail_msg: "nfs_mounts must be set by the including role."

- name: Mount shares directly on this host
  include_tasks: direct.yml
