---
- name: Assert nfs_mounts is set
  assert:
    that:
      - nfs_mounts | length > 0
    fail_msg: "nfs_mounts must be set by the including role."

- name: Mount shares directly on this host
  include_tasks: direct.yml
  when: nfs_mount_lxc_host is not defined

- name: Mount shares on the Proxmox host and bind into this LXC container
  include_tasks: lxc.yml
  when: nfs_mount_lxc_host is defined
