---
sonarr_user: media
sonarr_group: media
sonarr_installdir: /opt
sonarr_bindir: "{{ sonarr_installdir }}/Sonarr"
sonarr_datadir: /var/lib/sonarr/
sonarr_branch: main
sonarr_port: 8989
sonarr_umask: "0002"
