- import_playbook: mount_shares.yml

- name: Deploy sonarr
  hosts: sonarr
  roles:
    - sonarr

- name: Deploy radarr
  hosts: radarr
  roles:
    - radarr

- name: Deploy NZBGet
  hosts: nzbget
  roles:
    - nzbget
