# - name: Install dependencies
#   include_tasks: dependencies.yml
# 
# - name: Create technitium user
#   include_tasks: user.yml
# 
# - name: Install technitium
#   include_tasks: install.yml

- name: Firewall
  include_tasks: firewall.yml
